### PR TITLE
Fixes to run gorump on XEN

### PR DESCRIPTION
**Pull request by marinbek**
Hi

as discussed in the issue  #22, this contains:
- fix to run gorump on XEN (extending stack to include an empty `envp`)
- updated README a bit to contain more up-to-date instructions (reran whole process, works)
- updated README with instructions for running on XEN (networking etc.)
- updated Makefiles of examples to include `make xen` which creates `something-xen.bin` 

Cheers
M

### CODE REVIEW

**Comment by anttikantee** [comment]
As far as I know, with that patch there's no guarantee that the linker will arrange the symbols so that env follows argv.

**Comment by marinbek** [comment]
And what would be the best way to make sure it is always there?

So far I tested it with 5 different apps and it was ok every time, but with same toolchain.

**Comment by anttikantee** [comment]
Just put it in the same vector, i.e. argv[] = { "args", 0, "", 0 }; (or however the exact termination goes)

(or if you want to get really fancy, make it a struct, but I wouldn't bother)

It's a kludge anyway ... some day need to figure out how to get the Rumprun infra to arrange things in the "proper" way.

**Comment by marinbek** [comment]
Yeah that's what I thought but I thought it would be more "proper" (clear) this way. Thanks!

**Pull request merged**
